### ISSUE TITLE
Transactions by Address & Internal Transactions by Address

### ISSUE THREAD

**Issue by Rheannone** [geometry-labs/icon-addresses#54]
https://explorer.icon.geometry-dev.net/api/v1/transactions/address/hxfc56203484921c3b7a4dee9579d8614d8c8daaf5
https://explorer.icon.geometry-dev.net/api/v1/transactions/internal/address/hxfc56203484921c3b7a4dee9579d8614d8c8daaf5

coming back 504 1-2/3rds of the time

**Comment by Rheannone** [comment]
"pending" for very long as well: 
Request URL: https://explorer.icon.geometry-dev.net/api/v1/transactions

**Comment by pranav925** [comment]
The endpoints are timing out due to SQL optimizations, related to this issue: https://github.com/geometry-labs/icon-transactions/issues/94
