### ISSUE TITLE
Copy transaction count by address routine from transactions service

### ISSUE THREAD

**Issue by robcxyz** [geometry-labs/icon-addresses#59]
This is a random contract and was raised as a diff in Tx count and balance 

https://tracker.icon.foundation/contract/cx43e2eec79eb76293c298f2b17aec06097be606e0

https://tracker.icon.community/contract/cx43e2eec79eb76293c298f2b17aec06097be606e0

**Comment by pranav925** [comment]
The balance count diff is due to the current tracker not counting staked balance for contracts
