### ISSUE TITLE
Data issue with missing token for address

### ISSUE THREAD

**Issue by robcxyz** [geometry-labs/icon-addresses#61]
This query is missing a contract for WeBloc - https://tracker.icon.community/api/v1/addresses/address-tokens/hxc4193cda4a75526bf50896ec242d6713bb6b02a3

In the Foundation tracker we see 6 tokens - https://tracker.icon.foundation/address/hxc4193cda4a75526bf50896ec242d6713bb6b02a3

In ours we see 5 - https://tracker.icon.community/address/hxc4193cda4a75526bf50896ec242d6713bb6b02a3
(Missing weblock - https://tracker.icon.foundation/contract/cx921205acb7c51e16d5b7cbc37539a4357d929d20#readcontract)

**Comment by pranav925** [comment]
Should be fixed after recent addresses back fill (addresses-z2sw)
